variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  image: debian:stable-slim
  tags: ['docker']
  script:
    - apt-get update -yqqq && apt-get install -y python3-dev make virtualenv
    - make html
    - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
  except:
  - schedules
